

## POST
POST http://localhost:4004/MroSrv/VendorList
Content-Type: application/json;IEEE754Compatible=true

{
    "manufacturerCode":"100053",
    "localManufacturerCode":"433432",
    "countryCode":"IN"

}